name: Deploy Laravel Project

on:
  push:
    branches:
      - sistema_vps  # ou a branch que você usa para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files via SSH
      run: |
        rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/painel

    - name: Install Composer dependencies
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        cd /var/www/html/painel
        composer install --no-interaction --prefer-dist --optimize-autoloader
        EOF

    - name: Copy Env, Storage Link
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        cd /var/www/html/painel
        sudo chmod -R 777 /var/www/html/painel/*
        php artisan storage:link
        EOF
        
#    - name: Copy Seeders Vps
#      run: |
#        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
#        cp -r /var/www/html/painel/database/seeders_vps/* /var/www/html/painel/database/seeders
#        EOF

    - name: Set Permissions
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        sudo chown -R www-data:www-data /var/www/html/painel
        sudo chmod -R 775 /var/www/html/painel/storage
        sudo chmod -R 775 /var/www/html/painel/bootstrap/cache
        sudo chmod -R 777 /var/www/html/painel/*
        EOF

#    - name: Run Migrations
#      run: |
#        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
#        cd /var/www/html/painel
#        php artisan migrate:fresh --force
#        EOF

    - name: Run Optimize Clear and Cached
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        cd /var/www/html/painel
        php artisan optimize:clear
        php artisan route:cache
        php artisan view:cache
        EOF

    - name: Set Permissions
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        sudo chown -R www-data:www-data /var/www/html/painel
        sudo chmod -R 775 /var/www/html/painel/storage
        sudo chmod -R 775 /var/www/html/painel/bootstrap/cache
        sudo chmod -R 777 /var/www/html/painel/*
        EOF
